<a href="https://colab.research.google.com/github/BurningFalls/nlp-study/blob/main/BERT%20(E-book)/2_%EA%B5%AC%EA%B8%80_BERT%EC%9D%98_%EB%A7%88%EC%8A%A4%ED%81%AC%EB%93%9C_%EC%96%B8%EC%96%B4_%EB%AA%A8%EB%8D%B8(MLM_Masked_Language_Model)_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 36.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 64.1 MB/s eta 0:00:00


In [2]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [3]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [4]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

In [5]:
print(inputs['input_ids']) # 정수 인코딩 결과

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [6]:
print(inputs['token_type_ids']) # 세그먼트 인코딩 결과

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [7]:
print(inputs['attention_mask']) # 어텐션 마스크

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [8]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [9]:
pip('Soccer is a really fun [MASK]')

[{'score': 0.9753888845443726,
  'token': 1012,
  'token_str': '.',
  'sequence': 'soccer is a really fun.'},
 {'score': 0.014161552302539349,
  'token': 999,
  'token_str': '!',
  'sequence': 'soccer is a really fun!'},
 {'score': 0.009935013949871063,
  'token': 1025,
  'token_str': ';',
  'sequence': 'soccer is a really fun ;'},
 {'score': 0.0004769465886056423,
  'token': 1029,
  'token_str': '?',
  'sequence': 'soccer is a really fun?'},
 {'score': 1.8595392248244025e-05,
  'token': 2133,
  'token_str': '...',
  'sequence': 'soccer is a really fun...'}]

In [10]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.25629016757011414,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.1728406846523285,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.11107704043388367,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248982787132263,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046622782945633,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

In [11]:
pip('I went to [MASK] this morning.')

[{'score': 0.3573071360588074,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.23304429650306702,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.12845073640346527,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.0623057521879673,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.04695269465446472,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]